<?php
return [
    'color'=>[
        [
            'name'=>'红色',
            'code'=>'#FF0000',
        ],
        [
            'name'=>'橙色',
            'code'=>'#FF7F00',
        ],
        [
            'name'=>'黄色',
            'code'=>'#FFFF00',
        ],
        [
            'name'=>'绿色',
            'code'=>'#00FF00',
        ],
        [
            'name'=>'青色',
            'code'=>'#00FFFF',
        ],
        [
            'name'=>'蓝色',
            'code'=>'#0000FF',
        ],
        [
            'name'=>'紫色',
            'code'=>'#8B00FF',
        ],
    ]
];